version: '3.8'
services:
  auth-service:
    build: ./cmd/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
  loan-service:
    build: ./cmd/loan-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
  transaction-service:
    build: ./cmd/transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

